
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryan Lima
 */
public class FormPesquisa extends javax.swing.JFrame {

    Pesquisa pesq = new Pesquisa();
    
    public FormPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Idade = new javax.swing.JLabel();
        Opiniao = new javax.swing.JLabel();
        textIdade = new javax.swing.JTextField();
        textOpiniao = new javax.swing.JTextField();
        buttonOpiniao = new javax.swing.JButton();
        buttonRelat = new javax.swing.JButton();
        buttonSair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title1.setText("Pesquisa Cinema");

        Title2.setText("Filme: O tubarão vegano");

        Idade.setText("Sua idade:");

        Opiniao.setText("Opinião: 1- Otimo, 2- Bom, 3- Ruim");

        textIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdadeActionPerformed(evt);
            }
        });

        textOpiniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOpiniaoActionPerformed(evt);
            }
        });

        buttonOpiniao.setText("CADASTRAR OPINIÃO");
        buttonOpiniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpiniaoActionPerformed(evt);
            }
        });

        buttonRelat.setText("RELATÓRIO");
        buttonRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatActionPerformed(evt);
            }
        });

        buttonSair.setText("SAIR");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOpiniao)
                        .addGap(101, 101, 101)
                        .addComponent(buttonRelat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Opiniao)
                        .addGap(18, 18, 18)
                        .addComponent(textOpiniao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Idade)
                        .addGap(18, 18, 18)
                        .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title2)
                    .addComponent(Title1))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Title2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idade)
                    .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opiniao)
                    .addComponent(textOpiniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpiniao)
                    .addComponent(buttonRelat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textIdadeActionPerformed

    private void textOpiniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOpiniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOpiniaoActionPerformed

    private void buttonOpiniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpiniaoActionPerformed
        // TODO add your handling code here:
        try {
            int idade = Integer.parseInt(textIdade.getText());
            int opiniao = Integer.parseInt(textOpiniao.getText());
        
            pesq.SomarDados(idade);
            pesq.AnaliseOpcao(opiniao);
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite apenas numeros!");
        }
        catch(ArithmeticException e) {
            JOptionPane.showMessageDialog(null, "Erro de divisão por zero!");
        }
    }//GEN-LAST:event_buttonOpiniaoActionPerformed

    private void buttonRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatActionPerformed
        // TODO add your handling code here
        pesq.Relatorio();
    }//GEN-LAST:event_buttonRelatActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPesquisa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel Opiniao;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JButton buttonOpiniao;
    private javax.swing.JButton buttonRelat;
    private javax.swing.JToggleButton buttonSair;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textOpiniao;
    // End of variables declaration//GEN-END:variables
}
