
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADM
 */
public class FormAutonomo extends javax.swing.JFrame {
    
    Autonomo aut = new Autonomo();
    /**
     * Creates new form FomrAltonomo
     */
    public FormAutonomo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Registro = new javax.swing.JLabel();
        textRegistro = new javax.swing.JTextField();
        valorTotal = new javax.swing.JLabel();
        textValorTotal = new javax.swing.JTextField();
        Comissao = new javax.swing.JLabel();
        textComissao = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        textCalcular = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        botaoExibir = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Altonomo");

        Nome.setText("Nome:");

        textNome.addActionListener(this::textNomeActionPerformed);

        Registro.setText("Registro:");

        textRegistro.addActionListener(this::textRegistroActionPerformed);

        valorTotal.setText("Valor Total:");

        Comissao.setText("Comissão:");

        textComissao.addActionListener(this::textComissaoActionPerformed);

        botaoCalcular.setText("CALCULAR");
        botaoCalcular.addActionListener(this::botaoCalcularActionPerformed);

        textCalcular.addActionListener(this::textCalcularActionPerformed);

        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.addActionListener(this::botaoCadastrarActionPerformed);

        botaoExibir.setText("EXIBIR");
        botaoExibir.addActionListener(this::botaoExibirActionPerformed);

        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(this::botaoVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorTotal)
                        .addGap(18, 18, 18)
                        .addComponent(textValorTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Comissao)
                        .addGap(18, 18, 18)
                        .addComponent(textComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Registro)
                        .addGap(18, 18, 18)
                        .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(botaoCadastrar)
                        .addGap(66, 66, 66)
                        .addComponent(botaoExibir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCalcular)
                .addGap(28, 28, 28)
                .addComponent(textCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registro)
                    .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotal)
                    .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comissao)
                    .addComponent(textComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCalcular)
                    .addComponent(textCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoExibir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botaoVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRegistroActionPerformed

    private void textComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComissaoActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
   
        this.textCalcular.setText("" + aut.CalcularComissao());
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void textCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCalcularActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
      
        String nome_aut = this.textNome.getText();
        int reg_aut = Integer.parseInt(this.textRegistro.getText());
        double num_aut = Double.parseDouble(this.textValorTotal.getText());
        double vlr_aut = Double.parseDouble(this.textComissao.getText());
        
        aut.Cadastrar(nome_aut, reg_aut, num_aut, vlr_aut);
        
        this.textNome.setText("");
        this.textRegistro.setText("");
        this.textValorTotal.setText("");
        this.textComissao.setText("");
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExibirActionPerformed

        String dados = aut.Exibir();
        
        String[] info = dados.split(";");
        
        this.textNome.setText(info[0]);
        this.textRegistro.setText(info[1]);
        this.textValorTotal.setText(info[2]);
        this.textComissao.setText(info[3]);
    }//GEN-LAST:event_botaoExibirActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        new FormEmpresa().setVisible(true);

        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormAutonomo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comissao;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoExibir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textCalcular;
    private javax.swing.JTextField textComissao;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textRegistro;
    private javax.swing.JTextField textValorTotal;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
