/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alunocmc
 */
public class FormMensalista extends javax.swing.JFrame {

    Mensalista mens = new Mensalista();
    /**
     * Creates new form FormMensalista
     */
    public FormMensalista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Registro = new javax.swing.JLabel();
        textRegistro = new javax.swing.JTextField();
        SalarioBruto = new javax.swing.JLabel();
        textSalarioBruto = new javax.swing.JTextField();
        Desconto = new javax.swing.JLabel();
        textDesconto = new javax.swing.JTextField();
        botaovoltar = new javax.swing.JButton();
        calcularsalario = new javax.swing.JButton();
        botaocadastrar = new javax.swing.JButton();
        textSalario = new javax.swing.JTextField();
        botaoexibir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Funcionario Mensalista");

        Nome.setText("Nome:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        Registro.setText("Registro:");

        textRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRegistroActionPerformed(evt);
            }
        });

        SalarioBruto.setText("Salario Bruto:");

        Desconto.setText("Desconto:");

        botaovoltar.setText("VOLTAR");
        botaovoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaovoltarActionPerformed(evt);
            }
        });

        calcularsalario.setText("CALCULAR SALARIO");
        calcularsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularsalarioActionPerformed(evt);
            }
        });

        botaocadastrar.setText("CADASTRAR");
        botaocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocadastrarActionPerformed(evt);
            }
        });

        textSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSalarioActionPerformed(evt);
            }
        });

        botaoexibir.setText("EXIBIR");
        botaoexibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoexibirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaocadastrar)
                        .addGap(38, 38, 38)
                        .addComponent(botaoexibir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Desconto)
                                .addGap(18, 18, 18)
                                .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SalarioBruto)
                                .addGap(18, 18, 18)
                                .addComponent(textSalarioBruto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Registro)
                                    .addComponent(Nome))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNome)))))
                        .addGap(69, 69, 69)
                        .addComponent(calcularsalario)
                        .addGap(18, 18, 18)
                        .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaovoltar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registro)
                    .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalarioBruto)
                    .addComponent(textSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desconto)
                    .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularsalario)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaocadastrar)
                    .addComponent(botaoexibir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(botaovoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRegistroActionPerformed

    private void botaovoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaovoltarActionPerformed
        // Comando para chamar a interface e torna-lá visível
        new FormEmpresa().setVisible(true);
        // Este comando desabilita da memória a interface
        dispose();
    }//GEN-LAST:event_botaovoltarActionPerformed

    private void calcularsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularsalarioActionPerformed
        // Inserir no campo de texto do salario o retorno do método
        // com o salario calculado
        this.textSalario.setText("" + mens.CalcularSalario());
    }//GEN-LAST:event_calcularsalarioActionPerformed

    private void botaocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocadastrarActionPerformed
        // Buscando as informacoes nos campos de texto e 
        // atribuindo a variaveis onde getText() busca o conteudo do campo
        String nome_mens = this.textNome.getText();
        int reg_mens = Integer.parseInt(this.textRegistro.getText());
        double bs_mens = Double.parseDouble(this.textSalarioBruto.getText());
        double desc_mens = Double.parseDouble(this.textDesconto.getText());
        // Atravez da instancia de classe chamar o método Cadastrar
        // enviando as variaveis que o método requer
        mens.Cadastrar(nome_mens, reg_mens, bs_mens, desc_mens);
        // Limpar os campos onde o setText() é utilizado para colocar informações
        // nos campos de texto
        this.textNome.setText("");
        this.textRegistro.setText("");
        this.textSalarioBruto.setText("");
        this.textDesconto.setText("");
    }//GEN-LAST:event_botaocadastrarActionPerformed

    private void botaoexibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoexibirActionPerformed
        // Uma variavel tipo String recebe o retorno do método Exibir()
        String dados = mens.Exibir();
        // Um vetor é criado onde cada índice é alocado um valor que é
        // separado pela função split, onde o ";" é o delimitador das informações
        String[] info = dados.split(";");
        this.textNome.setText(info[0]);
        this.textRegistro.setText(info[1]);
        this.textSalarioBruto.setText(info[2]);
        this.textDesconto.setText(info[3]);
        
    }//GEN-LAST:event_botaoexibirActionPerformed

    private void textSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desconto;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel SalarioBruto;
    private javax.swing.JButton botaocadastrar;
    private javax.swing.JButton botaoexibir;
    private javax.swing.JButton botaovoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcularsalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textDesconto;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textRegistro;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textSalarioBruto;
    // End of variables declaration//GEN-END:variables
}
